version: 2.1

.vars:
  docker: &docker_vars
    image: artsolopov/$CIRCLE_PROJECT_REPONAME
    tag: $DOCKER_TAG

orbs:
  python: circleci/python@2.0.1
  node: circleci/node@5.0.0
  docker: circleci/docker@2.0.2

jobs:
  deps-and-test:
    executor:
      name: python/default
      tag: "3.7"

    docker:
      - image: cimg/python:3.7
      - image: cimg/postgres:10.19
        environment:
          POSTGRES_USER: trip_planner
          POSTGRES_DB: trip_planner_test

    environment:
      POSTGRES_USER: trip_planner
      POSTGRES_DB: trip_planner_test
      TESTDB: postgresql://trip_planner@localhost/trip_planner_test
      FLASK_APP: trip_planner

    steps:
      - checkout
      - run:
          command: sudo apt-get update && sudo apt-get -y install postgresql-client-12
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: poetry run pytest
          name: Test
      - run:
          command: poetry export -o requirements.txt
          name: Export requirements.txt
      - persist_to_workspace:
          root: .
          paths: requirements.txt

  build-assets:
    executor:
      name: node/default
      tag: "16.13"

    environment:
      NODE_ENV: production

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run rollup
          name: Rollup
      - persist_to_workspace:
          root: .
          paths:
            - trip_planner/static/assets

  build-docker:
    executor: docker/machine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - docker/check
      - run:
          name: Setup branch name
          command: |
            echo 'export DOCKER_TAG=$(echo $CIRCLE_BRANCH | tr "/" "-")' >> $BASH_ENV
      - docker/build:
          <<: *docker_vars
          image: artsolopov/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          <<: *docker_vars
          digest-path: /tmp/digest.txt
      - run:
          command: cat /tmp/digest.txt

workflows:
  main:
    jobs:
      - deps-and-test
      - build-assets
      - build-docker:
          requires:
            - deps-and-test
            - build-assets
