version: 2.1

.vars:
  docker: &docker_vars
    image: artsolopov/$CIRCLE_PROJECT_REPONAME
    tag: $DOCKER_TAG

orbs:
  python: circleci/python@0.2.1
  node: circleci/node@2.0.1
  docker: circleci/docker@1.0.1

jobs:
  deps-and-test:
    executor: python/default

    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:10.11
        environment:
          POSTGRES_USER: trip_planner
          POSTGRES_DB: trip_planner_test

    environment:
      POSTGRES_USER: trip_planner
      POSTGRES_DB: trip_planner_test
      TESTDB: postgresql://trip_planner@localhost/trip_planner_test
      FLASK_APP: trip_planner

    steps:
      - checkout
      - run:
          command: sudo apt-get update && sudo apt-get -y install postgresql-client-11
      - run:
          command: pip install pipenv
          name: Install pipenv
      - run:
          command: pipenv lock -r > requirements.prod.txt && pipenv lock -rd > requirements.dev.txt && cat requirements.*.txt > requirements.txt && cat requirements.txt
          name: Generate requirements files
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test
      - run:
          command: mv requirements.prod.txt requirements.txt
      - persist_to_workspace:
          root: .
          paths: requirements.txt

  build-assets:
    executor:
      name: node/default
      tag: "12.13"

    environment:
      NODE_ENV: production

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run gulp css
          name: Compile styles
      - run:
          command: npm run rollup
          name: Compile JS
      - persist_to_workspace:
          root: .
          paths:
            - trip_planner/static/css
            - trip_planner/static/js

  build-docker:
    executor: docker/machine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - docker/check
      - run:
          name: Setup branch name
          command: |
            echo 'export DOCKER_TAG=$(echo $CIRCLE_BRANCH | tr "/" "-")' >> $BASH_ENV
      - docker/build:
          <<: *docker_vars
          image: artsolopov/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          <<: *docker_vars
          digest-path: /tmp/digest.txt
      - run:
          command: cat /tmp/digest.txt

workflows:
  main:
    jobs:
      - deps-and-test
      - build-assets
      - build-docker:
          requires:
            - deps-and-test
            - build-assets
