"""Remove slug from trip

Revision ID: 362c777d6919
Revises: e0ab2374c1d2
Create Date: 2024-06-23 15:13:36.402606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362c777d6919'
down_revision = 'e0ab2374c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index('idx_trip_author_slug')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.create_index('idx_trip_author_slug', ['author_id', 'slug'], unique=False)

    # ### end Alembic commands ###
