"""Added center to trip

Revision ID: 4a0fe58677a9
Revises: f01b6854341b
Create Date: 2022-02-19 20:53:19.202561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0fe58677a9'
down_revision = 'f01b6854341b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('center_lat', sa.Numeric(precision=8, scale=5), nullable=True))
    op.add_column('trip', sa.Column('center_lon', sa.Numeric(precision=8, scale=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'center_lon')
    op.drop_column('trip', 'center_lat')
    # ### end Alembic commands ###
