"""Added key to Trip

Revision ID: 577ed6333051
Revises: 5ab8813b5e28
Create Date: 2023-06-10 01:09:49.683989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577ed6333051'
down_revision = '5ab8813b5e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('key', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_trip_key'), 'trip', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_key'), table_name='trip')
    op.drop_column('trip', 'key')
    # ### end Alembic commands ###
