"""Adding updated_at to points and trips

Revision ID: 58eabb673ad2
Revises: a6506f85f145
Create Date: 2024-07-07 17:16:26.870615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eabb673ad2'
down_revision = 'a6506f85f145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_point_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trip_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_updated_at'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_updated_at'))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
