"""Making slug nullable again

Revision ID: 5ab8813b5e28
Revises: 4a0fe58677a9
Create Date: 2023-06-09 23:01:54.659756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab8813b5e28'
down_revision = '4a0fe58677a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'slug',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'slug',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
