"""Added privacy options to Trip and Point

Revision ID: 6167b5c96ab3
Revises: 4a0fe58677a9
Create Date: 2023-04-04 00:10:42.830764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6167b5c96ab3'
down_revision = '4a0fe58677a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('privacy_status', sa.Enum('private', 'public', name='privacystatusenum', native_enum=False, length=255), server_default='private', nullable=False))
    op.add_column('trip', sa.Column('privacy_status', sa.Enum('private', 'public', name='privacystatusenum', native_enum=False, length=255), server_default='private', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'privacy_status')
    op.drop_column('point', 'privacy_status')
    # ### end Alembic commands ###
