"""Adding created_at to points and trips

Revision ID: a6506f85f145
Revises: 362c777d6919
Create Date: 2024-07-07 17:02:13.962583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6506f85f145'
down_revision = '362c777d6919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
