"""Adding new schedule field

Revision ID: b4b1ed4da917
Revises: 4410c334f8ab
Create Date: 2020-05-06 00:20:14.796817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b1ed4da917'
down_revision = '4410c334f8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('schedule', sa.JSON(none_as_null=True), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'schedule')
    # ### end Alembic commands ###
