"""Create trip points

Revision ID: bff937d0113d
Revises: da9e6155c3d6
Create Date: 2020-01-07 15:26:22.162521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff937d0113d'
down_revision = 'da9e6155c3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=2000), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_trip_id'), 'point', ['trip_id'], unique=False)
    op.create_index(op.f('ix_point_type'), 'point', ['type'], unique=False)
    op.create_index(op.f('ix_point_name'), 'point', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_name'), table_name='point')
    op.drop_index(op.f('ix_point_type'), table_name='point')
    op.drop_index(op.f('ix_point_trip_id'), table_name='point')
    op.drop_table('point')
    # ### end Alembic commands ###
