"""Adding websites to points

Revision ID: e0ab2374c1d2
Revises: 577ed6333051
Create Date: 2023-08-05 01:05:45.786700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0ab2374c1d2'
down_revision = '577ed6333051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('websites', postgresql.ARRAY(sa.String(length=2000)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_column('websites')

    # ### end Alembic commands ###
