"""Table maintenance

Revision ID: f01b6854341b
Revises: 8344badab728
Create Date: 2022-02-19 16:56:41.162795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f01b6854341b'
down_revision = '8344badab728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point', 'schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('point', 'schedule_old')
    op.create_index(op.f('ix_trip_name'), 'trip', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_name'), table_name='trip')
    op.add_column('point', sa.Column('schedule_old', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('point', 'schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###
