# Generated by Django 4.1 on 2022-08-09 19:03

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='longitude')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='longitude')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('notes', models.TextField()),
                ('slug', models.SlugField(max_length=500)),
                ('type', models.CharField(choices=[('museum', 'Museum'), ('sight', 'Sight'), ('entertainment', 'Entertainment'), ('food', 'Food'), ('accomodation', 'Accomodation'), ('transport', 'Transport'), ('shop', 'Shop'), ('other', 'Other')], max_length=255)),
                ('schedule', models.JSONField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
            ],
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['city', 'name'], name='locations_p_city_id_aa9c75_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['city', 'slug'], name='locations_p_city_id_dc6238_idx'),
        ),
    ]
