# Generated by Django 4.1 on 2022-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'verbose_name_plural': 'points of interest'},
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
