# Generated by Django 4.0.6 on 2022-07-08 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='longitude')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='longitude')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('notes', models.TextField()),
                ('slug', models.SlugField(max_length=500)),
                ('type', models.CharField(choices=[('museum', 'Museum'), ('sight', 'Sight'), ('entertainment', 'Entertainment'), ('food', 'Food'), ('accomodation', 'Accomodation'), ('transport', 'Transport'), ('shop', 'Shop'), ('other', 'Other')], max_length=255)),
                ('schedule', models.JSONField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.pointofinterest')),
                ('trip_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.tripleg')),
            ],
        ),
        migrations.AddIndex(
            model_name='tripleg',
            index=models.Index(fields=['trip', 'position'], name='trips_tripl_trip_id_673cdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripleg',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('trip'), django.db.models.expressions.F('position'), name='trip_leg_unique_trip_position'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['author', 'name'], name='trips_trip_author__f22579_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['author', 'slug'], name='trips_trip_author__a5e5e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('author'), django.db.models.expressions.F('slug'), name='trip_unique_author_slug'),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['city', 'name'], name='trips_point_city_id_b3f75b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['city', 'slug'], name='trips_point_city_id_b6efb3_idx'),
        ),
    ]
