name: Building

on:
  push:
    branches: [ master, deploy, github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  requirements_txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7.7
      - run: pip install poetry
      - name: Export requirements
        run: poetry export -o requirements.txt
      - name: Store requirements.txt file
        uses: actions/upload-artifact@v3
        with:
          name: requirements.txt
          path: requirements.txt
  assets:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13
      uses: actions/setup-node@v3
      with:
        node-version: 16.13
        cache: 'npm'
    - run: npm install
    - run: npm run rollup
    - name: Store compiled assets
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: trip_planner/static/assets
      

