name: Main workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13
      uses: actions/setup-node@v3
      with:
        node-version: 16.13
        cache: 'npm'
    - run: npm run rollup
    - name: Store compiled assets
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: trip_planner/static/assets
      

